# Application Configuration
# Configurazione Applicazione
# Generated at: 2025-10-02 10:11:35

spring:
  application:
    name: course-management-api
  
  # Database Configuration / Configurazione Database
  datasource:
    url: jdbc:postgresql://localhost:5432/course_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration / Configurazione JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Server Configuration / Configurazione Server
  servlet:
    context-path: /api
  
server:
  port: 8080

# Swagger/OpenAPI Configuration / Configurazione Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.esame

# Logging Configuration / Configurazione Logging
logging:
  level:
    com.esame: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
