# PostgreSQL Database Configuration
# Configurazione Database PostgreSQL
# Generated at: 2025-01-27

spring:
  profiles:
    active: postgres
  
  # PostgreSQL Database Configuration / Configurazione Database PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/course_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  # JPA/Hibernate Configuration / Configurazione JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# JWT Configuration / Configurazione JWT
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: 86400000  # 24 hours / 24 ore
    refresh-expiration: 604800000  # 7 days / 7 giorni

# Cache Configuration / Configurazione Cache
spring:
  cache:
    type: simple

# Mail Configuration / Configurazione Mail
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logging Configuration / Configurazione Logging
logging:
  level:
    com.esame: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/course-management.log
